### ISSUE TITLE
Jobs Incompatibility

### ISSUE THREAD

**Issue by TKwSni** [Minebench/HopperImprovements#2]
Is there a way to deny, the item move from hoppers to brewing stands and furnaces if the plugin jobs is detected and has the option to deny payments from these if items come from a hopper ?

https://github.com/Zrips/Jobs/issues/239

**Comment by Phoenix616** [comment]
If another plugin requires the InventoryMoveEvent then you can't completely disable it. Use the `cancel-move-event-if-full` config option instead. (And if another plugin doesn't respect cancelled events then that needs to be fixed in that plugin itself)
